name: Test Go code

on:
  push:
    paths: 
      - "**/*.go"
      - "go.mod"
      - "go.sum"

jobs:
  test:
    name: go test
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Golang
        uses: actions/setup-go@v5
        with: 
          go-version: "^1.22"
          check-latest: true
        
      - name: Run tests
        run: go test -v ./...
        